# Generated by Django 4.0.4 on 2022-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='teléfono'),
        ),
    ]
